env:
  es2021: true
extends:
  - airbnb
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
settings:
  import/parsers:
    '@typescript-eslint/parser':
      - '.ts'
      - '.tsx'
  import/resolver:
    typescript: {}
rules:
  # ------------------------------
  # Basic rules
  class-methods-use-this: 'off'
  no-unused-vars: 'off'
  '@typescript-eslint/no-unused-vars':
    - error
    - args: none
      varsIgnorePattern: '^_'
  no-unused-expressions:
    - error
    - allowShortCircuit: true
  no-use-before-define: 'off'
  '@typescript-eslint/no-use-before-define':
    - error
    - variables: false
  no-shadow: 'off'
  no-useless-constructor: 'off'
  '@typescript-eslint/no-useless-constructor': error
  no-empty-function: 'off'
  '@typescript-eslint/no-empty-function':
    - error
    - allow:
        - arrowFunctions
        - functions
        - methods
  # ------------------------------
  # Import rules
  import/order:
    - error
    - groups:
        - builtin
        - external
        - parent
        - sibling
        - index
      newlines-between: always
  import/prefer-default-export: 'off'
  import/extensions:
    - error
    - ignorePackages
    - js: never
      jsx: never
      ts: never
      tsx: never
  import/no-extraneous-dependencies: 'off'
