version: 2.1

orbs:
  node: circleci/node@4.1

executors:
  nodejs:
    docker:
      - image: cimg/node:15.1

commands:
  prepare:
    steps:
      - checkout
      - restore-crawler-cache
      - node/install-packages:
          pkg-manager: yarn

  restore-crawler-cache:
    steps:
      - restore_cache:
          keys:
            - crawler-data-v3

  save-crawler-cache:
    steps:
      - save_cache:
          key: crawler-data-v3
          paths:
            - packages/fkg-list-crawler/tmp

jobs:
  build-and-release:
    executor: nodejs
    steps:
      - add_ssh_keys:
          fingerprints:
            - 'b3:e8:3a:75:9d:0e:74:c6:e1:ca:5e:c5:24:81:d5:3a'

      - prepare

      - run:
          name: config github identity
          command: |
            git config --global user.email moonlight8978@gmail.com
            git config --global user.name _MoonLight_

      - run:
          name: build webapp, upload source map to error tracking service, then deploy
          command: |
            yarn build:webapp
            yarn upload:webapp:sourcemaps
            yarn deploy

      - save-crawler-cache

  build:
    executor: nodejs
    steps:
      - prepare

      - run:
          name: build
          command: yarn build:webapp

      - save-crawler-cache

workflows:
  release:
    jobs:
      - build-and-release:
          filters:
            branches:
              only: main
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - main
                - develop
                - /v.*/
                - /release.*/
