version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  build-and-release:
    docker:
      - image: cimg/node:15.1

    steps:
      - checkout

      - node/install-packages:
          pkg-manager: yarn

      - run:
          name: config github identity
          command: |
            git config --global user.email moonlight8978@gmail.com
            git config --global user.name _MoonLight_

      - run:
          name: deploy to github pages
          command: yarn deploy

workflows:
  release:
    jobs:
      - build-and-release:
          filters:
            branches:
              only: circleci-project-setup
