const NAME = 'NAME'
const VERSION = 'VERSION'
const ATTRIBUTE = 'ATTRIBUTE'
const LOVE = 'LOVE'
const NATION = 'NATION'
const SPEED = 'SPEED'
const STATS = 'STATS'
const SKILL = 'SKILL'
const ABILITIES = 'ABILITIES'

module.exports = {
  NAME, VERSION, ATTRIBUTE, LOVE, NATION, SPEED, STATS, SKILL, ABILITIES
}
