env:
  browser: true
  jest: true
globals:
  JSX: true
extends:
  - '../../.eslintrc.yml'
  - 'plugin:react/recommended'
  - plugin:react-hooks/recommended
plugins:
  - react
  - formatjs
rules:
  react/jsx-filename-extension:
    - error
    - extensions:
        - '.js'
        - '.jsx'
        - '.ts'
        - '.tsx'
  react/jsx-props-no-spreading: 'off'
  react/static-property-placement:
    - error
    - static public field
  react/react-in-jsx-scope: 'off'
  react/require-default-props: 'off'
  jsx-a11y/label-has-associated-control: 'off'
  'formatjs/no-offset': 'error'
